version: '3.9'

services:
  frontend_web1:
    build: ./functional-patterns-client/nyc-biomechanic_web1
    container_name: nyc-biomechanic_web1
    ports:
      - '81:5173'
    restart: always
    environment:
      - TZ=America/Los_Angeles
    networks:
      - nyc-biomechanics
    depends_on:
      - nginx

  frontend_web2:
    build: ./functional-patterns-client/nyc-biomechanic_web2
    container_name: nyc-biomechanic_web2
    ports:
      - '82:5173'
    restart: always
    environment:
      - TZ=America/Los_Angeles
    networks:
      - nyc-biomechanics
    depends_on:
      - nginx

  nginx:
    container_name: nyc-biomechanic_proxy
    build: ./functional-patterns-client/nginx
    environment:
      - TZ=America/Los_Angeles
    ports:
      - '7776:80'
    restart: always
    networks:
      - nyc-biomechanics
    depends_on:
      - backend

  backend:
    build: ./functional-pattern-backend
    container_name: nyc-biomechanic_backend
    environment:
      - TZ=America/Los_Angeles
    restart: always
    ports:
      - '9929:9929'
    networks:
      - nyc-biomechanics

  backend_proxy:
    build: ./functional-pattern-backend/nginx
    restart: unless-stopped
    ports:
      - 7777:80
    environment:
      - TZ=America/Los_Angeles
    networks:
      - nyc-biomechanics

  postgres:
    image: postgres
    container_name: nyc-biomechanic_database
    expose:
      - '5433'
    ports:
      - 5433:5433
    volumes:
      - /pool/nyc-biomechanics/functional-patterns-db/postgresql:/var/lib/postgresql/data
    environment:
      - TZ=America/Los_Angeles
      - POSTGRES_PASSWORD=vsJCsgxfeZqwrxJwx6Km
      - POSTGRES_USER=p3ab0dy
      - POSTGRES_DB=nyc-biomechanic
    command: -p 5433
    restart: always
    stdin_open: true
    tty: true
    networks:
      - nyc-biomechanics

networks:
  nyc-biomechanics:
    driver: bridge
